# バージョンを指定
version: "3.3"

# サービス定義
services:
  # サーバ
  web:
    build: ./src
    volumes:
      - ./src:/var/www/html
    ports:
      - 82:80


  # データベース
  db:
    image: mysql:5.7
    build: ./src
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: isaac
      MYSQL_PASSWORD: isaac
    ports:
      - 3308:3306
volumes:
  mysql: